work_dir: ./work_dir/trainloss/ntu/xview/agcn_joint_FCinit_2
model_saved_name: ./runs/trianloss/ntu_cv_agcn_joint_FCinit_2
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../../data/ntu/xview/train_data_joint.npy
  label_path: ../../data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../../data/ntu/xview/val_data_joint.npy
  label_path: ../../data/ntu/xview/val_label.pkl

# model
model: model.agcn.Model
old_model_path: ./runs/
numlayers: 20
numblocks: 20
model_args:
  topology: []
  blocksize: 30
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [4,5,6,7]
batch_size: 64
test_batch_size: 64
num_epoch: 50 
nesterov: True
#weights: ./runs/trianloss/ntu_cv_agcn_joint-7-2.pt
